### ISSUE TITLE
Controle op dubbelingen

### ISSUE THREAD

**Issue by mgraauw** [mgraauw/ADA-Lite-Geboortezorg#10]
In theorie kan in een valueSet in ART DECOR:
- dezelfde @code twee keer voorkomen
- twee @displayName leiden tot dezelfde @enum in ADA Lite
Bij conversie naar specs Lite is het goed als er een check is hierop, en een (fatale) fout komt.
Mocht dit voorkomen, kijken we hoe we het oplossen, kans is klein, dus signaleren is voldoende.

**Comment by xatapult** [comment]
@mgraauw Dubbele code komen niet voor, maar er blijken best vaak dubbele displaynames voor te komen, en de leiden dus weer naar dubbele enum waardes.

Bijvoorbeeld: kernset 23, concept `wijze_einde_zwangerschap`: Heeft dubbele entries met @displayName `medicamenteus` en `instrumenteel` (met verschillende codes). Voorzover ik het begrijp lijkt me dat sowieso een fout in de specificatie?!?

**Comment by xatapult** [comment]
Ik heb een apart issue #13 geopend om iets met die dubbele displaynames te doen.
