### ISSUE TITLE
Support voor adaextension element?

### ISSUE THREAD

**Issue by xatapult** [mgraauw/ADA-Lite-Geboortezorg#11]
In de readme kom ik het (to nu toe over het hoofd gezien) `<adaextension>` element tegen. 

ALs ik het goed begrijp mag dit voorkomen (nul of meer keer) aan het einde van een group, in een ADA Lite document.

De ADA Lite schemas/schematrons moeten hier dan dus wel rekening mee houden, dat doen ze nu niet. 

@mgraauw :

1. Moet dit in de schemas/schematrons voor lite documenten worden opgenomen?
1. ZIt dit ook in ADA full documenten en zo ja hoe?

Ik assign dit issue nu aan jou. Assign het maar aan mij als je de vragen beantwoord hebt.

**Comment by xatapult** [comment]
Moet ondersteund worden. Gekopieerd naar de full versie

**Comment by xatapult** [comment]
Wat is het model voor `<adaextension>`. Any attributes, any child elements?

**Comment by mgraauw** [comment]
Geen attributen, willekeurige children, geen namespace (of #any, mag ook).

**Comment by xatapult** [comment]
In de door de ART-DECOR schema generator gemaakte definities mogen er wél attributen in voorkomen: 
![image](https://user-images.githubusercontent.com/5820773/55059606-9ef59f80-506f-11e9-9889-6fcc623b9910.png)

**Comment by xatapult** [comment]
Het lijkt me dat we dit model maar moeten aanhouden?

**Comment by xatapult** [comment]
Alle schemas en schematrons ondersteunen nu het `<adaextension>` element.

Bij de transformatie van ada-lite naar ada-full wordt dit element één-op-één gekopieerd.
