### ISSUE TITLE
Maken HTML weergave ADA berichten

### ISSUE THREAD

**Issue by xatapult** [mgraauw/ADA-Lite-Geboortezorg#16]
Van de ADA berichten moet een HTML weergave kunnen worden gemaakt. Een *viewer* weergave.

Er zijn PDF weergave voorbeelden, bijvoorbeeld: https://github.com/Nictiz/Geboortezorg/blob/master/hl7_2_pdf/2_1/overdracht_acute_fase_bericht/doc/Scenario%20S05-AW-ada-text.pdf

Er is een keuze voor de implementatie:

- De vraag is of dit door leveranciers met een XSL instructie in de XML wordt gehangen. In dat geval moeten we de stylesheets hiervoor genereren m.b.v. de specs
- Of kunnen we een generieke stylesheet maken die mb.v. de spec en de data de pagina genereert

Resultaten toevoegen als een aparte tak in deze repo: `ada-viewer`

Een mockup voorbeeld van een html weergave is nog: https://www.marcdegraauw.com/babyconnectview.html

Marc maakt enkele meer volledige voorbeelden.

**Comment by xatapult** [comment]
Aanvullende eisen:

- Op basis van ADA lite
- Kolombreedtes instelbaar
- Conversies op sommige data elementen (bv. dagen ==> 2w3d)

**Comment by xatapult** [comment]
Marc maakt eerst een aantal meer volledige data voorbeelden

**Comment by xatapult** [comment]
Er staan nu voorbeelden in `design/examples-full-22` die als basis gebruikt kunnen worden voor volledige datasets. Deze moeten nog wel aangepast worden om correcte ADA lite berichten te worden.

**Comment by xatapult** [comment]
Dit is even geparkeerd omdat een aantal zaken niet duidelijk waren.

**Comment by xatapult** [comment]
Er is een viewer conversie gemaakt op basis van een eerdere (PDF/XSL-FO) viewer weergave van een ouder ADA bericht. Helaas waren niet alle codes/OIDs te mappen naar de nieuwe weergave.
[DEV-view-verloskundig-dossier-23-result.zip](https://github.com/mgraauw/ADA-Lite-Geboortezorg/files/3181705/DEV-view-verloskundig-dossier-23-result.zip)

**Comment by mgraauw** [comment]
Werkt, maar niet alle conceptId's zijn goed.

**Comment by AndersNiklasHolmberg** [comment]
Hmm, hoe moet ik dat dan anders doen ?

Verstuurd vanaf mijn iPhone

> Op 5 jul. 2019 om 14:06 heeft Marc de Graauw <notifications@github.com> het volgende geschreven:
> 
> Werkt, maar niet alle conceptId's zijn goed.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 


**Disclaimer*

*Aan dit bericht (inclusief attachments) kunnen geen 
rechten worden ontleend. Het bericht is alleen bestemd voor de 
geadresseerde. Indien dit bericht niet voor u is bestemd, verzoeken wij u 
vriendelijk dit onmiddellijk aan ons te melden en de e-mail inclusief 
attachments te vernietigen.

The contents of this message,  as well as any 
enclosures, are addressed personally to, and thus solely intended for the 
addressee and shall not constitute any obligations. A recipient who is 
neither the addressee, nor empowered to receive this message on behalf of 
the addressee, is kindly requested to immediately inform the sender of 
receipt and to destroy the email. **

**Comment by mgraauw** [comment]
Niet meer in scope.
