### ISSUE TITLE
Naam van veel elementen in schema's eindigen op "-start", dit zorgt voor problemen bij codegeneratie

### ISSUE THREAD

**Issue by mjbosman** [mgraauw/ADA-Lite-Geboortezorg#18]
Het karakter '-' levert problemen op bij het omzetten van een schema naar C# code. Is het suffix "-start" noodzakelijk? In de vorige release waren deze suffixen niet aanwezig.

![image](https://user-images.githubusercontent.com/49057298/55216532-494efd80-51fd-11e9-9e83-d0213d52bb12.png)

**Comment by mgraauw** [comment]
Dit zit ook niet in de schemas-simple-lite
