### ISSUE TITLE
ConceptId en OID suffix

### ISSUE THREAD

**Issue by mjbosman** [mgraauw/ADA-Lite-Geboortezorg#19]
In de nieuwe schema's is het conceptId weer aanwezig? Moet deze er in blijven? Zijn de OID suffixen ook noodzakelijk?

![image](https://user-images.githubusercontent.com/49057298/55217016-a9926f00-51fe-11e9-9ce2-a86fbd954e0d.png)

**Comment by mgraauw** [comment]
In schemas-simple-lite zit een schema zonder oid suffix en waar conceptId optioneel is. Zie ook:
https://github.com/mgraauw/ADA-Lite-Geboortezorg/tree/master/ada-lite
daar staan in de doc de verschillende schema's toegelicht. schemas-simple-lite is eigenlijk schema dat je zou moeten kiezen. Maar kijk of dit werkt voor jullie zonder de types.

De oid suffix kunnen we daar weglaten omdat de types anonymous zijn (het is een grote tree). Anders kan dat niet, want dan krijg je mogelijk dubbelingen (twee keer medicatie_type in andere context). Beperken tot het laatste cijfer (dus: zorgverlening_type_4), zou wel kunnen.

Ik wil eigenlijk nog feedback van leveranciers verzamelen en dan pas een versie 1.o maken, dus voel je vrij om wijzigingsvoorstellen in te brengen.

**Comment by mgraauw** [comment]
Is inbegrepen in issue #20
