### ISSUE TITLE
Expliciete types ipv Russian doll

### ISSUE THREAD

**Issue by mgraauw** [mgraauw/ADA-Lite-Geboortezorg#20]
Schema's aanpasssen. Zie voorbeeld.

**Comment by mgraauw** [comment]
En type namen volgens: vrouw_6
waarbij 6 laatste deel van de oid van concept/@id is.

**Comment by xatapult** [comment]
En: rename `schemas` directory ==> `schemas-art-decor`

Docu aanpassen!

**Comment by xatapult** [comment]
Voorbeeld van een ouder schema dat met de juiste structuur: 

[kernset-ada-release.zip](https://github.com/mgraauw/ADA-Lite-Geboortezorg/files/3038353/kernset-ada-release.zip)

**Comment by xatapult** [comment]
Done
