### ISSUE TITLE
Converteren HL7 V2 naar ADA

### ISSUE THREAD

**Issue by xatapult** [mgraauw/ADA-Lite-Geboortezorg#21]

**Comment by xatapult** [comment]
Openstaande vragen: 

1. In het verloskundig dossier zijn er voor gegevens als telefoonnummer/email vd vrouw geen velden. Klopt dat? Ik vraag het omdat dit soort gegevens wel in het Astraia HL7V2 bericht kunnen zitten. Ik vind het wat raar dat de gegevens vd vrouw in het ADA formaat zo incompleet ogen.
2. de spreadsheet met over te nemen gegevens staan gegevens die overgenomen moeten worden, zonder informatie over waar ze in het ADA bericht heen moeten en zonder dat ik een logische plek kan vinden. Enig idee?
   1. row 7: verwijzer/aanvrager gegevens
   2. row 9: result status
   3. row. 23: Goedkeuring
   4. row. 24 diagnose
   5. row. 25: Conclusie/advies
   6. row. 26 PDF echo verslag (we hadden afgesproken dat we dat in een apart bestand zouden zetten en een verwijzing in het ADA bericht, maar in welk veld moet die verwijzing?)
3. Er zijn twee velden in het ADA bericht voor pariteit: pariteit & pariteit_voor_deze_zwangerschap. Naar welke moet de pariteit uit het HL7V2 bericht toe?
4. Er komen gegevens in de groep <foetusspecifieke_onderzoeksgegevens> (per kind voor een meerling). Die heeft verplicht een <foetus_identificatie> nodig. Dat moet een identifier zijn. Wat moet ik daar invullen?
5. Spreadsheet rg 15 en verder: In het HL7V2 bericht staan percentielen, in het ADA bericht zitten hiervoor velden, maar in het commentaar in de spreadsheet wordt aangegeven dat er geen geschikt veld voor is? Mogen de percentielen uit het HL7V2 bericht wel overgenomen worden?
6. De velden ligging en placentalokalisatie zijn enums. Hoe kom ik aan een conversie(tabel) van de waardes in het HL7 V2 bericht naar die van het ADA bericht? Zelf bedenken? (lijkt me gezien mijn afwezige medische kennis niet een heel goed idee…)

**Comment by xatapult** [comment]
[Astraia ORU bericht toelichting.xlsx](https://github.com/mgraauw/ADA-Lite-Geboortezorg/files/3092954/Astraia.ORU.bericht.toelichting.xlsx)


[example.hl7.txt](https://github.com/mgraauw/ADA-Lite-Geboortezorg/files/3092957/example.hl7.txt)

**Comment by mgraauw** [comment]
Ad 1: Toegevoegd
Ad 2: Ik heb een aparte transactie gemaakt, zie:
https://decor.nictiz.nl/decor/services/RetrieveTransaction?id=2.16.840.1.113883.2.4.3.11.60.90.77.4.2480&effectiveDate=2019-05-06T15:45:28&language=nl-NL&ui=nl-NL&format=html&hidecolumns=45ghijklmnop
row 7: zit er nu in
row 9: weglaten
row 23: weglaten
row 24 + 25: doe maar even in opmerkingen, met "DIAGNOSIS: " en "CONCLUSION: " ervoor, op aparte regels. Velden voor definitieve oplossing zijn aangevraagd.
Ad 3, 4: opgelost in nieuwe transactie
Ad 5: overnemen in nieuwe transactie. Percentiel TCD is aangevraagd, voorlopig weglaten. 
Ad 6: zal ik overleggen met Astraia

**Comment by mgraauw** [comment]
Ad 5: percentielen wel overnemen, even met een voorlopige code (staat denk ik ook in ART DECOR)

**Comment by xatapult** [comment]
@mgraauw In het V2 bericht komen bij meerlingen per kind gegevens voor. Dus het veld `<foetusspecifieke_onderzoeksgegevens>` zal herhaalbaar moeten worden?

**Comment by xatapult** [comment]
Er ontbreken nog een paar in ADA verplichte velden in de invoer:

- `<datum_bepaling_a_terme_datum>` Hiervoor heb ik de onderzoeksdatum ingevuld, maar dat hoeft natuurlijk niet te kloppen. Dat kan ook al eerder gebeurd zijn.
- `<a_terme_datum_obv>` Er zijn geen gegevens beschikbaar over hoe de a-terme datum is vastgesteld. Waarde nu vastgezet op "Other", maar eigenlijk zou je een "Onbekend" als waarde willen hebben. Die is er echter niet, waarom niet?

**Comment by xatapult** [comment]
Waardes in een ADA bericht staan in attributen. Het is dus niet handig daar newlines in te plaatsen, omdat XML verwerking attribuut waardes mag normaliseren. Nu opgelost door ipv een newline een `/` te gebruiken.

**Comment by mgraauw** [comment]
> Er ontbreken nog een paar in ADA verplichte velden in de invoer:
> * `<datum_bepaling_a_terme_datum>` Hiervoor heb ik de onderzoeksdatum ingevuld, maar dat hoeft natuurlijk niet te kloppen. Dat kan ook al eerder gebeurd zijn.

Dat is prima zo.

> * `<a_terme_datum_obv>` Er zijn geen gegevens beschikbaar over hoe de a-terme datum is vastgesteld. Waarde nu vastgezet op "Other", maar eigenlijk zou je een "Onbekend" als waarde willen hebben. Die is er echter niet, waarom niet?

De waarde is in dit geval altijd '31541000146106', zie:
http://decor.nictiz.nl/decor/services/RetrieveValueSet?prefix=peri20-&id=2.16.840.1.113883.2.4.11.240&effectiveDate=2017-06-08T15:30:50&version=&format=html&language=nl-NL&seetype=live-services

Mag je vast zo invullen (voor dit bericht).

**Comment by mgraauw** [comment]
Waar zittten die newlines? Dit is niet zo'n goede oplossing, maar er is toch al een use case voor text values in ada concept, misschien beter dat uitwerken. B.v. <text> child onder het concept, waarbij dan @value leeg moet zijn. Of text content en @value leeg.

**Comment by xatapult** [comment]
Newlines zitten bijvoorbeeld hier, in je eigen voorstel:

>row 24 + 25: doe maar even in opmerkingen, met "DIAGNOSIS: " en "CONCLUSION: " ervoor, op aparte regels. 

Verder zijn er meldingen in het ASTRAIA bericht gecodeerd met `\.br`:

```
OBX|20|TX|CONCLUSION||De beperkingen van het echoscopisch onderzoek zijn besproken.\.br\clinte  priv\.br\||||||F
```

Het lijkt me dat dit toch newlines voorstellen...

**Comment by xatapult** [comment]
>B.v. child onder het concept, waarbij dan @value leeg moet zijn. Of text content en @value leeg.

Hmmm. Dat betekent een refactoring van ons ADA Lite fabriekje: Schema's en Schematrons gaan dus veranderen, want dat moet dan wel mogen.

**Comment by mgraauw** [comment]
v2 conversie is niet meer in scope is, voorlopig sluiten.
