### ISSUE TITLE
Herstel fouten verloskundig dossier

### ISSUE THREAD

**Issue by xatapult** [mgraauw/ADA-Lite-Geboortezorg#23]
In de definitie van het verloskundig dossier 23 lijken diverse fouten te zitten. Onderstaande lijst is wat is gevonden, mogelijk zijn er meer dingen mis:

- Verplichte elementen die (waarschijnlijk) niet verplicht horen te zijn:
  - `soort_drugs`
  - `trisomie_in_de_anamneseq`
- Het element `medisch_onderzoek` bevat meerdere velden die (waarschijnlijk) onterecht als verplicht zijn aangemerkt. Bovendien ontbreken er waardenlijsten voor een aantal van deze velden.

**Comment by mgraauw** [comment]
Toevoegen:
telefoonnummer
email vd vrouw
Check van de rest.

**Comment by mgraauw** [comment]
Aangegeven items hersteld, ook alles nog eens nagelopen. Zit nog niet in een release.

**Comment by mgraauw** [comment]
Fixed
