### ISSUE TITLE
diff laat groepen niet zien

### ISSUE THREAD

**Issue by mgraauw** [mgraauw/ADA-Lite-Geboortezorg#24]
Als een groep is toegevoegd/verwijderd, zie je alleen bij de groep erboven 'Nieuw' of 'Verwijderd'.
Maar de groep zelf komt niet terug. B.v. in dit overzicht:
file:///C:/Users/Marc/Desktop/diff-acute-overdracht21-kernset23.html
zie je wel dat 'Overdrachtdetails' is verwijderd, en 'Postnatale fase' nieuw, maar deze groepen zijn niet te zien.
Dat maakt dat je toch niet alle wijzigingen in detail ziet. Graag de groepen toevoegen, met dan in het kopje of zo 'Hele groep verwijderd' c.q. 'toegevoegd' en 'Verwijderd' of 'Nieuw' bij alle items daarin. Mag eventueel een optie zijn, zodat je een smalle en brede diff hebt. Bij smalle diff is dan ook niet van belang:
- verplaatste items
- ongewijzigde items

**Comment by mgraauw** [comment]
Ook trouwens aardige toevoeging: kort overzicht in tabel bovenin met totaal aantal groepen, items, codelijstitems van bron1 en bron2, dan zie je kort over wat voor omvang het gaat.

**Comment by xatapult** [comment]
Aangepast. De Github homepage https://mgraauw.github.io/ADA-Lite-Geboortezorg/ linkt nu naar zowel het volledige als het vereenvoudigde formaat.
