### ISSUE TITLE
Prio1 huidig  spec mist a terme datum

### ISSUE THREAD

**Issue by mjbosman** [mgraauw/ADA-Lite-Geboortezorg#25]
Er kan geen a terme datum worden vastgelegd volgens de "Prio1-huidig" spec. In het Babyconnect Viewer mockup scherm is de a termedatum wel opgenomen. Welke is juist?

![image](https://user-images.githubusercontent.com/49057298/58940454-c789cc00-8779-11e9-9217-4f16038c64f2.png)

**Comment by mgraauw** [comment]
A terme datum hoort er wel bij, dus de spec is onvolledig. Ik zal het (volgende week) herstellen.

**Comment by mgraauw** [comment]
Fixed

**Comment by mgraauw** [comment]
Fix op fix: a_terme_datum_groep stond niet op de juiste plek, is hersteld.
