### ISSUE TITLE
Overbodige namespace

### ISSUE THREAD

**Issue by mgraauw** [mgraauw/ADA-Lite-Geboortezorg#26]
In sommige specs (b.v.
https://github.com/mgraauw/ADA-Lite-Geboortezorg/blob/master/ada-lite/specs-simplified/kernset-23.xml)
staat een namespace alleen op conceptList:
<conceptList xmlns:bc-alg="https://babyconnect.org/ns/ada-lite-geboortezorg">
Beter overal namespaceloos te werken, je weet maar nooit of dit doorwerkt in software van leveranciers.

**Comment by mgraauw** [comment]
@Erik pakken we samen op in Groningen.

**Comment by xatapult** [comment]
Er miste een`exclude-result-prefixes="#all"` attribut op het `<xsl:stylesheet>`  element van `design/xsl/spec-full2spec-lite.xsl`
