### ISSUE TITLE
Schemas lite displayName

### ISSUE THREAD

**Issue by mgraauw** [mgraauw/ADA-Lite-Geboortezorg#27]
Schemas lite geven een foutmelding als displayName niet letterlijk klopt.
B.v.:
Value 'Strippen' is not facet-valid with respect to enumeration '[Sweeping of membrane (procedure), Induction of labour by artificial rupture of membranes (procedure), Cervical ripening with balloon (procedure), Cervical ripening with Prostaglandin E2 (procedure), Oxytocin induction of labour (procedure), Prostaglandin induction of labour (procedure), Elective caesarean section (procedure), Overig, Geen informatie]'. It must be a value from the enumeration.

Vaak worden NL vertalingen gebruikt, bovendien moeten we dit niet op typo's afkeuren.

**Comment by xatapult** [comment]
Ehhh, Tsja. Maar het is enumeration, geen vrij invulveld.

**Comment by mgraauw** [comment]
We kijken er vrijdag naar.

**Comment by mgraauw** [comment]
Fixed
