### ISSUE TITLE
One root element for all transactions

### ISSUE THREAD

**Issue by joostfaassen** [mgraauw/ADA-Lite-Geboortezorg#37]
Based on my understanding, the concept of "transactions" will eventually be removed from ADA lite, and a single root element (`<ada_lite />` maybe?) will be used for all ADA lite documents. Is this correct?

**Comment by mgraauw** [comment]
Just checked, the name of the root element already does not matter, you can call it <ada_lite> or <joost> or whatever you like. The @transactionRef does matter: if the goal is to submit a kernset, the appropriate value must be provided.

**Comment by joostfaassen** [comment]
Perfect, thanks!

Just for understanding it properly: where exactly does the @transactionRef get picked up in the kernset transformation? Is this during ada-lite to ada-full, or in ada-full to hl7v3 (in which case the transactionRef could just be hardcoded in the hl7v3 xslts)

**Comment by mgraauw** [comment]
Both. ADA full root element will be ```<kernset>```, based on transactionRef, and HL7 conversion uses it too. And I can't hardcode it anyway, I need something to decide which xslt to use for the conversion. And touching the full ADA format is not wise, too much software (both in and out of my control) depends on that already.
