### ISSUE TITLE
~adaextension~ to ada_extension

### ISSUE THREAD

**Issue by joostfaassen** [mgraauw/ADA-Lite-Geboortezorg#38]
As seen in the [README extension example](https://github.com/mgraauw/ADA-Lite-Geboortezorg#extensies):

Can we rename `adaextension` to `ada_extension` or just `extension`? `skype-id` then also becomes `skype_id` following the [snake casing](https://en.wikipedia.org/wiki/Snake_case) of all other elements in the ADA format. This helps to keep our OCD in check :-)

**Comment by mgraauw** [comment]
OK, we'll do that. ada_extension, extension is more likely to provide reserved name clashes.

**Comment by mgraauw** [comment]
Unfortunately this has already landed in the ART-DECOR software at Nictiz. Too risky to change now, won't be fixed.
