### ISSUE TITLE
Support voor enums

### ISSUE THREAD

**Issue by mgraauw** [mgraauw/ADA-Lite-Geboortezorg#4]
Zie: https://github.com/mgraauw/ADA-Lite-Geboortezorg#enums
enums zijn een alternatief voor aanlevering met value.

Wat nodig is:
- genereren van enums in de schema's
- zie design/schemas/kernset-ada-lite.xsd voor een ruwe draft

**Comment by xatapult** [comment]
Opmerkingen/vragen:

- De waardes van de enums afleiden uit `@displayName`?
- Dit gaat dus over het ADA-lite formaat?
- `ada-lite2ada-full.xsl` moet dantoch ook aan aangepast worden, of heb ik het mis?

**Comment by mgraauw** [comment]
Klopt. Voor afleiden naam ben ik nog niet zeker of dat met de shortName routine uit ADA moet of niet.

**Comment by xatapult** [comment]
enum is normalize-space + spaties vervangen door _

**Comment by xatapult** [comment]
Evt. de shortname routine gebruiken later.

**Comment by xatapult** [comment]
example-empty generator aanpassen? ook enums toevoegen als van toepassing? Of twee lege voorbeelden genereren

**Comment by xatapult** [comment]
We krijgen nu enums als `Neurologische_bloedingen:_o.a._subarachnoidale_bloedingen/aneurysma_pre-existent`...

Niet echt lekker

**Comment by mgraauw** [comment]
Probeer dan maar met de shortName routine

**Comment by xatapult** [comment]
Dat ziet er al beter uit

**Comment by xatapult** [comment]
- Enums worden meegenomen in de van toepassing zijnde schemas en schematrons
- In de empty examples worden op de juiste plekken ook enum attributen gegenereerd
- Conversie van ADA lite naar full aangepast op gebruik enum attributen
- Delen van de code voor hergebruik ondergebracht in een aparte bibliotheek `xsl/xsl-common.xsl`
- Overal duidelijker start commentaar gegenereerd + consistente naamgeving
