### ISSUE TITLE
Eenvoudige schema's voor ADA Lite

### ISSUE THREAD

**Issue by mgraauw** [mgraauw/ADA-Lite-Geboortezorg#5]
Sommige leveranciers gebruiken de schema's ook voor codegeneratie, en dan werken de complexere full ADA schema's niet fijn. Zie design/schemas/kernset-ada-lite.xsd voor een voorbeeld.
En design/xsl/art-decor/release2liteschema.xsl voor een draft schemagenerator.

Gebruik van standaard ART DECOR tools voor deze schema's moeten we maar loslaten, laten we die wel gebruiken voor full ADA schema's.

**Comment by xatapult** [comment]
Tbv de schematron generatie genereer ik eerst een relatief eenvoudig maar wel geldig schema, zowel voor de full als voor de lite versie. Is het geen idee om dit schema te gebruiken als simple schema?

Het gegenereerde schema gebruikt benoemde complex types om zaken vast te leggen. Het is (jin mijn ervaring) voor code generatie over het algemeen eenvoudiger om definities gewoon te nesten (russian doll aanpak). Is er een reden voor de benoemde complex types?

**Comment by mgraauw** [comment]
Beide voorstellen zijn OK. Misschien voor russian doll ook even feedback van Vrumun (dat is die mail) bekijken.

**Comment by xatapult** [comment]
Generator toevoegen, maar hoe we het precies gaan invullen is nog onduidelijk

**Comment by xatapult** [comment]
schemas tak moet schemas-full worden

Toevoegen schemas-lite tak

**Comment by xatapult** [comment]
Toegevoegd. Ze staan in de directories:

- `schemas-simple-lite`
- `schemas-simple-full`

De directory `schemas` blijft gewoon bestaan. 

De naamgeving aanpassen en ze "lite" en "full" noemen zou suggereren dat ze bedoeld zijn voor full en lite ADA documenten en dat klopt niet. We hebben een complexe/volledige en een simpele variant.
