### ISSUE TITLE
Support kernset 2.3, voorgaande zwangerschap 2.2

### ISSUE THREAD

**Issue by mgraauw** [mgraauw/ADA-Lite-Geboortezorg#6]
Deze 2 transacties kunnen ook gegenereerd worden, zie:
https://github.com/mgraauw/ADA-Lite-Geboortezorg#todo

De links naar ART-DECOR staan eronder, als je format=html vervangt door =xml krijg je de specs.

**Comment by xatapult** [comment]
2? Op de todo lijst staan er 4. Wat bedoel je precies?

**Comment by mgraauw** [comment]
Er zijn er pas 2 op ART DECOR beschikbaar.

**Comment by xatapult** [comment]
@mgraauw Ik heb kernset 2.3 kunnen toevoegen, maar de links in de readme naar: 

* Verloskundig dossier PWD 2.3
* Samenvatting voorgaande zwangerschap PWD 2.2
* Samenvatting voorgaande zwangerschap PWD 2.3

lopen allemaal dood. Graag een seintje als ik hier mee verder kan.

**Comment by mgraauw** [comment]
De links doen het nu. Wel volgen vanaf de git repo, heb de pages niet bijgewerkt (moet dat nog even uitvinden).

**Comment by xatapult** [comment]
@mgraauw : De Github Pages worden ook gegenereerd, dus daar hoef (en moet) je niets rechtstreeks aan bijwerken.

**Comment by xatapult** [comment]
Alle specs uit de todo lijst bijgevoegd + verschil rapportage generatie.
