### ISSUE TITLE
Toelichting op gebruik tools

### ISSUE THREAD

**Issue by mgraauw** [mgraauw/ADA-Lite-Geboortezorg#7]
Voor leveranciers moet er nog docu komen hoe ze e.e.a. gebruiken:
- de schematron
- full ADA generator

**Comment by xatapult** [comment]
- Vanaf niveau installeren Saxon. Dit moet ook beschreven worden.
- Genereren van de validatie XSL met het Schematron straatje, Dus de XSL die de SVRL oplevert

**Comment by mgraauw** [comment]
https://www.art-decor.org/mediawiki/index.php?title=Schematron-validation

**Comment by xatapult** [comment]
We plaatsen hiervoor een readme in de ada-lite tak van de repo

**Comment by xatapult** [comment]
Ook de omzetting van ada-lite naar ada-full documenteren

**Comment by xatapult** [comment]
Er is nu een uitgebreide readme in de ada-lite tak.

**Let op:** De bron voor deze readme is design/documentation/README-ada-lite.md
Aanpassingen daar doen dus.
