### ISSUE TITLE
Opstellen en toevoegen copyright tekst

### ISSUE THREAD

**Issue by xatapult** [mgraauw/ADA-Lite-Geboortezorg#9]
Er moet een geschikte copyright tekst worden toegevoegd aan alle stylesheets . Deze moet ook worden geplaatst in de gegenereerde zaken als Schematrons en XSDs.

1. @mgraauw bepaalt de juiste tekst
1. @eriksiegel zorgt dat deze over verwerkt wordt

@mgraauw: Issue is nu voor jou. Als je de tekst hebt bepaat zet deze in dit issue en assign het issue vervolgens aan mij.

**Comment by xatapult** [comment]
Het in-genereren van een copyright notice heb ik al wel toegevoegd voor alle gegenereerde stylsheets, schemas en schematrons.

 Je kunt deze tekst zelf aanpassen in het bestandje `design/xsl/lib/copyright.txt`

Wel moet er nog de copyright notice worden toegevoegd aan de xsl-s in de design tak. Kwestie van copy/paste als de tekst definitief is.

**Comment by mgraauw** [comment]
Done, in copyright.txt, jouw naam er ook bijgezet dus kijk er even naar voor jouw akkoord.

**Comment by xatapult** [comment]
Ook toegevoegd aan de stylesheets
